# Numpy Assignment

1- Create three lists representing house features, each list containing ten values. The first one for the house's size in square meters, the second one for rooms and last for price. Then, create an array combining these lists.

2- Transpose the array you have created, so that every line can represent features of one house.

3- Display the shape of the array and explain what it means.
For the following assignment, you are going to use Earthquakes dataset.

4- Load the Earthquakes dataset. Export the dataset to an array as you covered in the previous lesson.

5- Slice first 20 rows and column numbers 3, 5, 6, 7, 12. Then, assign the array you sliced to a variable.

6- Display the row numbers where last values are equal to 4.5 or higher.

7- Assign 1 to first row.

8- Save the final state of the array to disk. You are going to use this in the next assignment.

9- Load the array you saved in the previous lesson from the disk.

10- Display the mean and the standard deviation for each column.

11- Subtract 1, 25, 25, 10, 4 from columns in order. (Remember it can be dobe in one line of code.)

12- Multiply each element by 2. (Remember it can be done in one line of code.)

In [561]:
import numpy as np

## Create three lists representing house features, 

Each list containing ten values. The first one for the house's size in square meters, the second one for rooms and last for price. Then, create an array combining these lists.

In [562]:
square_foot_list = [1100, 1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900, 2000]
rooms_list = [i for i in np.arange(3,13)]
price_list = [20000 * i for i in np.arange(1,11)]
raw_house_data = np.array(\
            [square_foot_list,rooms_list,price_list])

print("length of square foot_list", len(square_foot_list))
print("length of rooms_list", len(rooms_list))
print("length of price_list", len(price_list))
print("shape of data structure ", raw_house_data.shape)
print("Array = ", raw_house_data)

length of square foot_list 10
length of rooms_list 10
length of price_list 10
shape of data structure  (3, 10)
Array =  [[  1100   1200   1300   1400   1500   1600   1700   1800   1900   2000]
 [     3      4      5      6      7      8      9     10     11     12]
 [ 20000  40000  60000  80000 100000 120000 140000 160000 180000 200000]]


## Transpose the array you have created

So that every line can represent features of one house.


In [563]:
raw_house_data = raw_house_data.copy().T
print("shape = ", raw_house_data.shape)
print("array tranposed is ", raw_house_data)


shape =  (10, 3)
array tranposed is  [[  1100      3  20000]
 [  1200      4  40000]
 [  1300      5  60000]
 [  1400      6  80000]
 [  1500      7 100000]
 [  1600      8 120000]
 [  1700      9 140000]
 [  1800     10 160000]
 [  1900     11 180000]
 [  2000     12 200000]]


## Display shape of array and explain what it means.

In [564]:
print("Shape of house data is ", house_data.shape, "\n")
explamation  = """The Array has been changed into a matrix that we can split apart.
It can be split into features ( size, root ) and dependent (price). 
"""
print(explamation)

Shape of house data is  (10, 3) 

The Array has been changed into a matrix that we can split apart.
It can be split into features ( size, root ) and dependent (price). 



## Load the Earthquakes dataset. 
* Export the dataset to an array as you covered in the previous 
lesson.
*Load the Earthquakes dataset. 
*Export the dataset to an array as you covered in the previous lesson.

It was 100 time easy to use pandas and convert into a numpy array.

In [565]:
import pandas as pd
pd_csv_data = pd.read_csv("earthquakes1970-2014.csv")
np_csv_data = pd_csv_data.to_numpy()
np_csv_data.shape

(5304, 12)

In [566]:
pd_csv_data.head(20)

DateTime  Latitude  Longitude  Depth  Magnitude MagType  \
0   1970/01/04 17:00:40.20   24.1390   102.5030   31.0        7.5      Ms   
1   1970/01/06 05:35:51.80   -9.6280   151.4580    8.0        6.2      Ms   
2   1970/01/08 17:12:39.10  -34.7410   178.5680  179.0        6.1      Mb   
3   1970/01/10 12:07:08.60    6.8250   126.7370   73.0        6.1      Mb   
4   1970/01/16 08:05:39.00   60.2800  -152.6600   85.0        6.0      ML   
5   1970/01/20 07:19:51.20  -25.8000  -177.3490   80.0        6.5      Mb   
6   1970/01/20 17:33:05.40   42.5190   142.9660   46.0        6.4      Ms   
7   1970/01/21 17:51:38.50    7.0170  -104.2980   33.0        6.6      Ms   
8   1970/01/26 10:01:20.50  -12.5790   166.3700   50.0        6.4      Ms   
9   1970/02/04 05:08:48.00   15.5320   -99.4840   21.0        6.5      Ms   
10  1970/02/05 22:05:58.30   12.5980   122.1170   11.0        6.6      Ms   
11  1970/02/06 22:10:41.60   23.0960   100.7750   33.0        6.1      Ms   
12  1970/02/24 02:07:36.80   30.5760   103.0310   33.0        6.0      Ms   
13  1970/02/27 07:07:56.50   50.1300  -179.5898    7.0        6.0      ML   
14  1970/02/28 10:52:31.10   52.5898  -175.0400  161.0        6.1      ML   
15  1970/03/04 03:30:35.40   12.1340   143.7070   33.0        6.2      Ms   
16  1970/03/09 16:01:10.50  -19.0080   168.6030   41.0        6.5      Ms   
17  1970/03/10 04:58:26.20   44.7980   148.8700   40.0        6.0      Mb   
18  1970/03/11 22:38:32.40   57.3900  -153.9700   16.0        6.5      ML   
19  1970/03/15 12:39:17.80  -29.6530   -69.4990  119.0        6.0      Mb   

    NbStations  Gap  Distance  RMS Source       EventID  
0         90.0  NaN       NaN  0.0    NEI  1.970010e+09  
1         85.0  NaN       NaN  0.0    NEI  1.970011e+09  
2         59.0  NaN       NaN  0.0    NEI  1.970011e+09  
3         91.0  NaN       NaN  0.0    NEI  1.970011e+09  
4          0.0  NaN       NaN  NaN     AK           NaN  
5        175.0  NaN       NaN  0.0    NEI  1.970012e+09  
6        199.0  NaN       NaN  0.0    NEI  1.970012e+09  
7        140.0  NaN       NaN  0.0    NEI  1.970012e+09  
8         91.0  NaN       NaN  0.0    NEI  1.970013e+09  
9        100.0  NaN       NaN  0.0    NEI  1.970020e+09  
10        94.0  NaN       NaN  0.0    NEI  1.970021e+09  
11        57.0  NaN       NaN  0.0    NEI  1.970021e+09  
12        94.0  NaN       NaN  0.0    NEI  1.970022e+09  
13         0.0  NaN       NaN  NaN     AK           NaN  
14         0.0  NaN       NaN  NaN     AK           NaN  
15        82.0  NaN       NaN  0.0    NEI  1.970030e+09  
16        61.0  NaN       NaN  0.0    NEI  1.970031e+09  
17        65.0  NaN       NaN  0.0    NEI  1.970031e+09  
18         0.0  NaN       NaN  NaN     AK           NaN  
19       118.0  NaN       NaN  0.0    NEI  1.970032e+09

In [567]:
pd_csv_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5304 entries, 0 to 5303
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   DateTime    5304 non-null   object 
 1   Latitude    5304 non-null   float64
 2   Longitude   5304 non-null   float64
 3   Depth       5304 non-null   float64
 4   Magnitude   5304 non-null   float64
 5   MagType     5304 non-null   object 
 6   NbStations  5250 non-null   float64
 7   Gap         172 non-null    float64
 8   Distance    170 non-null    float64
 9   RMS         5264 non-null   float64
 10  Source      5304 non-null   object 
 11  EventID     5242 non-null   float64
dtypes: float64(9), object(3)
memory usage: 497.4+ KB


## Slice 
first 20 rows and column numbers 3, 5, 6, 7, 12. Then, assign the array you sliced to a variable.

In [568]:
print("Convert to 0 index since 12 is out of bounds: Shape ", \
      np_csv_data.shape)
print("The shape of the original data is ", np_csv_data.shape);

data = np_csv_data[:20,[2,4,5,6,11] ]

print("The shape of the new data is ", data.shape)
data

Convert to 0 index since 12 is out of bounds: Shape  (5304, 12)
The shape of the original data is  (5304, 12)
The shape of the new data is  (20, 5)


array([[102.503, 7.5, 'Ms', 90.0, 1970010440.0],
       [151.458, 6.2, 'Ms', 85.0, 1970010640.0],
       [178.568, 6.1, 'Mb', 59.0, 1970010840.0],
       [126.736999999999, 6.1, 'Mb', 91.0, 1970011040.0],
       [-152.66, 6.0, 'ML', 0.0, nan],
       [-177.348999999999, 6.5, 'Mb', 175.0, 1970012040.0],
       [142.966, 6.4, 'Ms', 199.0, 1970012040.0],
       [-104.298, 6.6, 'Ms', 140.0, 1970012140.0],
       [166.37, 6.4, 'Ms', 91.0, 1970012640.0],
       [-99.48399999999991, 6.5, 'Ms', 100.0, 1970020440.0],
       [122.117, 6.6, 'Ms', 94.0, 1970020540.0],
       [100.775, 6.1, 'Ms', 57.0, 1970020640.0],
       [103.031, 6.0, 'Ms', 94.0, 1970022440.0],
       [-179.5898, 6.0, 'ML', 0.0, nan],
       [-175.039999999999, 6.1, 'ML', 0.0, nan],
       [143.706999999999, 6.2, 'Ms', 82.0, 1970030440.0],
       [168.603, 6.5, 'Ms', 61.0, 1970030940.0],
       [148.87, 6.0, 'Mb', 65.0, 1970031040.0],
       [-153.97, 6.5, 'ML', 0.0, nan],
       [-69.49899999999991, 6.0, 'Mb', 118.0, 197003154

## Display the row numbers 

where last values are equal to 4.5 or higher.


In [569]:
# Problem -- I do not understand the question.
# I have tried several different ideas, but I am not able to get a 
# good answer.  My plan is to discuss during office hours or after 
# next week and move on to the next probleem

## Assign 1 to first row.


In [593]:
data[0,:] = 1
data

array([[1, 1, 1, 1, 1],
       [151.458, 6.2, 'Ms', 85.0, 1970010640.0],
       [178.568, 6.1, 'Mb', 59.0, 1970010840.0],
       [126.736999999999, 6.1, 'Mb', 91.0, 1970011040.0],
       [-152.66, 6.0, 'ML', 0.0, nan],
       [-177.348999999999, 6.5, 'Mb', 175.0, 1970012040.0],
       [142.966, 6.4, 'Ms', 199.0, 1970012040.0],
       [-104.298, 6.6, 'Ms', 140.0, 1970012140.0],
       [166.37, 6.4, 'Ms', 91.0, 1970012640.0],
       [-99.48399999999991, 6.5, 'Ms', 100.0, 1970020440.0],
       [122.117, 6.6, 'Ms', 94.0, 1970020540.0],
       [100.775, 6.1, 'Ms', 57.0, 1970020640.0],
       [103.031, 6.0, 'Ms', 94.0, 1970022440.0],
       [-179.5898, 6.0, 'ML', 0.0, nan],
       [-175.039999999999, 6.1, 'ML', 0.0, nan],
       [143.706999999999, 6.2, 'Ms', 82.0, 1970030440.0],
       [168.603, 6.5, 'Ms', 61.0, 1970030940.0],
       [148.87, 6.0, 'Mb', 65.0, 1970031040.0],
       [-153.97, 6.5, 'ML', 0.0, nan],
       [-69.49899999999991, 6.0, 'Mb', 118.0, 1970031540.0]], dtype=object)

## Save the final state of the array to disk. 

You are going to use this in the next assignment.


In [571]:
# Tried to save them all to string and convert them in the next 
# assignment, but it failed.  Has to resort to pandas to get the 
# numpy with the correct datatype
#np.savetxt('data.csv', data, delimiter=',',fmt="%s")
import pandas as pd
dataframe_to_save = pd.DataFrame(data)
dataframe_to_save.to_csv("data.csv", index=False)
data


array([[1, 1, 1, 1, 1],
       [151.458, 6.2, 'Ms', 85.0, 1970010640.0],
       [178.568, 6.1, 'Mb', 59.0, 1970010840.0],
       [126.736999999999, 6.1, 'Mb', 91.0, 1970011040.0],
       [-152.66, 6.0, 'ML', 0.0, nan],
       [-177.348999999999, 6.5, 'Mb', 175.0, 1970012040.0],
       [142.966, 6.4, 'Ms', 199.0, 1970012040.0],
       [-104.298, 6.6, 'Ms', 140.0, 1970012140.0],
       [166.37, 6.4, 'Ms', 91.0, 1970012640.0],
       [-99.48399999999991, 6.5, 'Ms', 100.0, 1970020440.0],
       [122.117, 6.6, 'Ms', 94.0, 1970020540.0],
       [100.775, 6.1, 'Ms', 57.0, 1970020640.0],
       [103.031, 6.0, 'Ms', 94.0, 1970022440.0],
       [-179.5898, 6.0, 'ML', 0.0, nan],
       [-175.039999999999, 6.1, 'ML', 0.0, nan],
       [143.706999999999, 6.2, 'Ms', 82.0, 1970030440.0],
       [168.603, 6.5, 'Ms', 61.0, 1970030940.0],
       [148.87, 6.0, 'Mb', 65.0, 1970031040.0],
       [-153.97, 6.5, 'ML', 0.0, nan],
       [-69.49899999999991, 6.0, 'Mb', 118.0, 1970031540.0]], dtype=object)

## Load the array you saved from the disk.

<b>The values array will be loaded as a Strings and will the datatype
    changed for each column</b>

<b>I have tried several ways and could not create a ndArray with multiple datatypes like Pandas could.</b>

#### Best attempt at create a datatype with multiple datatypes 
When column stack was called all columns were converted to string
``` python
test2 = array_from_file.transpose()
a = np.copy(test2[0]).astype(float).reshape(-1,1)
b = np.copy(test2[1]).astype(float).reshape(-1,1)
c = np.copy(test2[2]).astype(str).reshape(-1,1)

test3 = np.column_stack((a,b,c))
print("first row = ", test3[0])
print("Shape = ", test3.shape)
```

In [572]:
# Could not use this 
# array_from_file = np.loadtxt('data.csv', delimiter=',', dtype=str)
import pandas as pd
raw_csv_data = pd.read_csv("data.csv", index_col=False)
raw_csv_data

0    1   2      3             4
0     1.0000  1.0   1    1.0  1.000000e+00
1   151.4580  6.2  Ms   85.0  1.970011e+09
2   178.5680  6.1  Mb   59.0  1.970011e+09
3   126.7370  6.1  Mb   91.0  1.970011e+09
4  -152.6600  6.0  ML    0.0           NaN
5  -177.3490  6.5  Mb  175.0  1.970012e+09
6   142.9660  6.4  Ms  199.0  1.970012e+09
7  -104.2980  6.6  Ms  140.0  1.970012e+09
8   166.3700  6.4  Ms   91.0  1.970013e+09
9   -99.4840  6.5  Ms  100.0  1.970020e+09
10  122.1170  6.6  Ms   94.0  1.970021e+09
11  100.7750  6.1  Ms   57.0  1.970021e+09
12  103.0310  6.0  Ms   94.0  1.970022e+09
13 -179.5898  6.0  ML    0.0           NaN
14 -175.0400  6.1  ML    0.0           NaN
15  143.7070  6.2  Ms   82.0  1.970030e+09
16  168.6030  6.5  Ms   61.0  1.970031e+09
17  148.8700  6.0  Mb   65.0  1.970031e+09
18 -153.9700  6.5  ML    0.0           NaN
19  -69.4990  6.0  Mb  118.0  1.970032e+09

In [573]:
np_csv_data = raw_csv_data.to_numpy()
np_csv_data

array([[1.0, 1.0, '1', 1.0, 1.0],
       [151.458, 6.2, 'Ms', 85.0, 1970010640.0],
       [178.568, 6.1, 'Mb', 59.0, 1970010840.0],
       [126.736999999999, 6.1, 'Mb', 91.0, 1970011040.0],
       [-152.66, 6.0, 'ML', 0.0, nan],
       [-177.348999999999, 6.5, 'Mb', 175.0, 1970012040.0],
       [142.966, 6.4, 'Ms', 199.0, 1970012040.0],
       [-104.298, 6.6, 'Ms', 140.0, 1970012140.0],
       [166.37, 6.4, 'Ms', 91.0, 1970012640.0],
       [-99.48399999999992, 6.5, 'Ms', 100.0, 1970020440.0],
       [122.117, 6.6, 'Ms', 94.0, 1970020540.0],
       [100.775, 6.1, 'Ms', 57.0, 1970020640.0],
       [103.031, 6.0, 'Ms', 94.0, 1970022440.0],
       [-179.5898, 6.0, 'ML', 0.0, nan],
       [-175.039999999999, 6.1, 'ML', 0.0, nan],
       [143.706999999999, 6.2, 'Ms', 82.0, 1970030440.0],
       [168.603, 6.5, 'Ms', 61.0, 1970030940.0],
       [148.87, 6.0, 'Mb', 65.0, 1970031040.0],
       [-153.97, 6.5, 'ML', 0.0, nan],
       [-69.49899999999991, 6.0, 'Mb', 118.0, 1970031540.0]], dtype=ob

## Display mean, standard deviation for each column.

Note the last column contains nan so it not a number

In [589]:
# Preprocessing -- Remove third column since it is a String
numeric_data = np.delete(np_csv_data, 2, axis=1)

# Calculate the mean
print(type(numeric_data.mean(axis=0)))
print("Mean of columns: ", np.round(numeric_data.mean(axis=0),2))

# Preprocessing -- Need to remomve the NaN std was failing
numeric_data_without_nan=np.nan_to_num(numeric_data_without_nan, nan=0)

# Calculate the Standard Deviation
print("Standard Deviation of Columns ",numeric_data_without_nan.std(axis=0))

<class 'numpy.ndarray'>


TypeError: loop of ufunc does not support argument 0 of type float which has no callable rint method

## Subtract 1, 25, 25, 10, 4 from columns in order. 

(Remember it can be done in one line of code.)

In [575]:
# Preprocessing remove the third element (25) since the third is a
# string and we cannot use the minus operator on a string
# However, we will use the result from above

numeric_data - [1,25,10,4]


array([[0.0, -24.0, -9.0, -3.0],
       [150.458, -18.8, 75.0, 1970010636.0],
       [177.568, -18.9, 49.0, 1970010836.0],
       [125.736999999999, -18.9, 81.0, 1970011036.0],
       [-153.66, -19.0, -10.0, nan],
       [-178.348999999999, -18.5, 165.0, 1970012036.0],
       [141.966, -18.6, 189.0, 1970012036.0],
       [-105.298, -18.4, 130.0, 1970012136.0],
       [165.37, -18.6, 81.0, 1970012636.0],
       [-100.48399999999992, -18.5, 90.0, 1970020436.0],
       [121.117, -18.4, 84.0, 1970020536.0],
       [99.775, -18.9, 47.0, 1970020636.0],
       [102.031, -19.0, 84.0, 1970022436.0],
       [-180.5898, -19.0, -10.0, nan],
       [-176.039999999999, -18.9, -10.0, nan],
       [142.706999999999, -18.8, 72.0, 1970030436.0],
       [167.603, -18.5, 51.0, 1970030936.0],
       [147.87, -19.0, 55.0, 1970031036.0],
       [-154.97, -18.5, -10.0, nan],
       [-70.49899999999991, -19.0, 108.0, 1970031536.0]], dtype=object)

## Multiply each element by 2. 

(Remember it can be done in one line of code.)

In [576]:
numeric_data * 2

array([[2.0, 2.0, 2.0, 2.0],
       [302.916, 12.4, 170.0, 3940021280.0],
       [357.136, 12.2, 118.0, 3940021680.0],
       [253.473999999998, 12.2, 182.0, 3940022080.0],
       [-305.32, 12.0, 0.0, nan],
       [-354.697999999998, 13.0, 350.0, 3940024080.0],
       [285.932, 12.8, 398.0, 3940024080.0],
       [-208.596, 13.2, 280.0, 3940024280.0],
       [332.74, 12.8, 182.0, 3940025280.0],
       [-198.96799999999985, 13.0, 200.0, 3940040880.0],
       [244.234, 13.2, 188.0, 3940041080.0],
       [201.55, 12.2, 114.0, 3940041280.0],
       [206.062, 12.0, 188.0, 3940044880.0],
       [-359.1796, 12.0, 0.0, nan],
       [-350.079999999998, 12.2, 0.0, nan],
       [287.413999999998, 12.4, 164.0, 3940060880.0],
       [337.206, 13.0, 122.0, 3940061880.0],
       [297.74, 12.0, 130.0, 3940062080.0],
       [-307.94, 13.0, 0.0, nan],
       [-138.99799999999982, 12.0, 236.0, 3940063080.0]], dtype=object)