# Numpy Assignment

1- Create three lists representing house features, each list containing ten values. The first one for the house's size in square meters, the second one for rooms and last for price. Then, create an array combining these lists.

2- Transpose the array you have created, so that every line can represent features of one house.

3- Display the shape of the array and explain what it means.
For the following assignment, you are going to use Earthquakes dataset.

4- Load the Earthquakes dataset. Export the dataset to an array as you covered in the previous lesson.

5- Slice first 20 rows and column numbers 3, 5, 6, 7, 12. Then, assign the array you sliced to a variable.

6- Display the row numbers where last values are equal to 4.5 or higher.

7- Assign 1 to first row.

8- Save the final state of the array to disk. You are going to use this in the next assignment.

9- Load the array you saved in the previous lesson from the disk.

10- Display the mean and the standard deviation for each column.

11- Subtract 1, 25, 25, 10, 4 from columns in order. (Remember it can be dobe in one line of code.)

12- Multiply each element by 2. (Remember it can be done in one line of code.)

In [6]:
import numpy as np

## Create three lists representing house features, 

Each list containing ten values. The first one for the house's size in square meters, the second one for rooms and last for price. Then, create an array combining these lists.

In [7]:
square_foot_list = [1100, 1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900, 2000]
rooms_list = [i for i in np.arange(3,13)]
price_list = [20000 * i for i in np.arange(1,11)]
raw_house_data = np.array(\
            [square_foot_list,rooms_list,price_list])

print("length of square foot_list", len(square_foot_list))
print("length of rooms_list", len(rooms_list))
print("length of price_list", len(price_list))
print("shape of data structure ", raw_house_data.shape)
print("Array = ", raw_house_data)

length of square foot_list 10
length of rooms_list 10
length of price_list 10
shape of data structure  (3, 10)
Array =  [[  1100   1200   1300   1400   1500   1600   1700   1800   1900   2000]
 [     3      4      5      6      7      8      9     10     11     12]
 [ 20000  40000  60000  80000 100000 120000 140000 160000 180000 200000]]


## Transpose the array you have created

So that every line can represent features of one house.


In [8]:
raw_house_data = raw_house_data.copy().T
print("shape = ", raw_house_data.shape)
print("array tranposed is ", raw_house_data)


shape =  (10, 3)
array tranposed is  [[  1100      3  20000]
 [  1200      4  40000]
 [  1300      5  60000]
 [  1400      6  80000]
 [  1500      7 100000]
 [  1600      8 120000]
 [  1700      9 140000]
 [  1800     10 160000]
 [  1900     11 180000]
 [  2000     12 200000]]


## Display shape of array and explain what it means.

In [9]:
print("Shape of house data is ", raw_house_data.shape, "\n")
explamation  = """The Array has been changed into a matrix that we can split apart.
It can be split into features ( size, root ) and dependent (price). 
"""
print(explamation)

Shape of house data is  (10, 3) 

The Array has been changed into a matrix that we can split apart.
It can be split into features ( size, root ) and dependent (price). 



## Load the Earthquakes dataset. 
* Export the dataset to an array as you covered in the previous 
lesson.
*Load the Earthquakes dataset. 
*Export the dataset to an array as you covered in the previous lesson.

It was 100 time easy to use pandas and convert into a numpy array.

In [10]:
import pandas as pd
pd_csv_data = pd.read_csv("earthquakes1970-2014.csv")
np_csv_data = pd_csv_data.to_numpy()
np_csv_data.shape

FileNotFoundError: [Errno 2] No such file or directory: 'earthquakes1970-2014.csv'

In [ ]:
pd_csv_data.head(20)

In [ ]:
pd_csv_data.info()

## Slice 
first 20 rows and column numbers 3, 5, 6, 7, 12. Then, assign the array you sliced to a variable.

In [ ]:
print("Convert to 0 index since 12 is out of bounds: Shape ", \
      np_csv_data.shape)
print("The shape of the original data is ", np_csv_data.shape);

data = np_csv_data[:20,[2,4,5,6,11] ]

print("The shape of the new data is ", data.shape)
data

## Display the row numbers 

where last values are equal to 4.5 or higher.


In [ ]:
# Problem -- I do not understand the question.
# I have tried several different ideas, but I am not able to get a 
# good answer.  My plan is to discuss during office hours or after 
# next week and move on to the next probleem

## Assign 1 to first row.


In [ ]:
data[0,:] = 1
data

## Save the final state of the array to disk. 

You are going to use this in the next assignment.


In [ ]:
# Tried to save them all to string and convert them in the next 
# assignment, but it failed.  Has to resort to pandas to get the 
# numpy with the correct datatype
#np.savetxt('data.csv', data, delimiter=',',fmt="%s")
import pandas as pd
dataframe_to_save = pd.DataFrame(data)
dataframe_to_save.to_csv("data.csv", index=False)
data


## Load the array you saved from the disk.

<b>The values array will be loaded as a Strings and will the datatype
    changed for each column</b>

<b>I have tried several ways and could not create a ndArray with multiple datatypes like Pandas could.</b>

#### Best attempt at create a datatype with multiple datatypes 
When column stack was called all columns were converted to string
``` python
test2 = array_from_file.transpose()
a = np.copy(test2[0]).astype(float).reshape(-1,1)
b = np.copy(test2[1]).astype(float).reshape(-1,1)
c = np.copy(test2[2]).astype(str).reshape(-1,1)

test3 = np.column_stack((a,b,c))
print("first row = ", test3[0])
print("Shape = ", test3.shape)
```

In [ ]:
# Could not use this 
# array_from_file = np.loadtxt('data.csv', delimiter=',', dtype=str)
import pandas as pd
raw_csv_data = pd.read_csv("data.csv", index_col=False)
raw_csv_data

In [ ]:
np_csv_data = raw_csv_data.to_numpy()
np_csv_data

## Display mean, standard deviation for each column.

Note the last column contains nan so it not a number

In [ ]:
# Preprocessing -- Remove third column since it is a String
numeric_data = np.delete(np_csv_data, 2, axis=1)

# Calculate the mean
print(type(numeric_data.mean(axis=0)))
print("Mean of columns: ", np.round(numeric_data.mean(axis=0),2))

# Preprocessing -- Need to remomve the NaN std was failing
numeric_data_without_nan=np.nan_to_num(numeric_data_without_nan, nan=0)

# Calculate the Standard Deviation
print("Standard Deviation of Columns ",numeric_data_without_nan.std(axis=0))

## Subtract 1, 25, 25, 10, 4 from columns in order. 

(Remember it can be done in one line of code.)

In [ ]:
# Preprocessing remove the third element (25) since the third is a
# string and we cannot use the minus operator on a string
# However, we will use the result from above

numeric_data - [1,25,10,4]


## Multiply each element by 2. 

(Remember it can be done in one line of code.)

In [ ]:
numeric_data * 2